const PRODUCTS = [
  // ── For the Classic Mom (Floral & Elegant) ──────────────────
  { title: "Pink & Purple Daisy Embroidery Set", description: "A stunning set of pink and purple daisy designs, perfect for spring apparel and home décor. Commercial licence included.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/09/14/Pink-Purple-Daisy-Embroidery-Set-Embroidery-130729541-1.jpg", affiliate: "https://www.creativefabrica.com/product/pink-purple-daisy-embroidery-set/ref/20531415/", category: "floral" },
  { title: "Red Rose Embroidery Design", description: "Classic red rose machine embroidery design — timeless and elegant, ideal for tote bags, apparel, and gifts.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/09/14/Red-Rose-Embroidery-Design-Embroidery-130744090-1.jpg", affiliate: "https://www.creativefabrica.com/product/red-rose-embroidery-design-3/ref/20531415/", category: "floral" },
  { title: "Sunflower Love", description: "Bright, cheerful sunflower design bursting with warmth. Makes a gorgeous gift stitched on a kitchen towel or tote.", image: "https://www.creativefabrica.com/wp-content/uploads/2021/05/10/Sunflower-Love-Embroidery-11877574-1.jpg", affiliate: "https://www.creativefabrica.com/product/sunflower-love-4/ref/20531415/", category: "floral" },
  { title: "Heart Petal Floral Embroidery Design", description: "A whimsical floral with heart-shaped petals — unique, modern, and perfect for personalized gifts.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/09/14/Heart-Petal-Floral-Embroidery-Design-Embroidery-130729648-1.jpg", affiliate: "https://www.creativefabrica.com/product/heart-petal-floral-embroidery-design/ref/20531415/", category: "floral" },
  { title: "Elegant Orange Floral Embroidery", description: "Bold, contemporary floral design in vibrant orange — makes a striking statement on denim or linen.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/09/15/Elegant-Orange-Floral-Embroidery-Embroidery-130818141-1.png", affiliate: "https://www.creativefabrica.com/product/elegant-orange-floral-embroidery/ref/20531415/", category: "floral" },
  { title: "Mama with Floral Frame", description: "The word 'Mama' beautifully enclosed in a delicate floral frame — a heartfelt gift for any mom.", image: "https://www.creativefabrica.com/wp-content/uploads/2023/11/29/Mama-with-Floral-Frame-Embroidery-85290125-1.jpg", affiliate: "https://www.creativefabrica.com/product/mama-with-floral-frame/ref/20531415/", category: "floral" },
  { title: "Blooming Rose Embroidery Design", description: "A fully blooming rose in stunning detail — ideal for pillowcases, aprons, and canvas bags.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/09/14/Blooming-Rose-Embroidery-Design-Embroidery-130730152-1.jpg", affiliate: "https://www.creativefabrica.com/product/blooming-rose-embroidery-design/ref/20531415/", category: "floral" },
  { title: "Floral Happy Mother's Day", description: "A complete 'Happy Mother's Day' greeting wrapped in floral elegance — stitch it on a pillow or shirt.", image: "https://www.creativefabrica.com/wp-content/uploads/2021/04/15/Floral-Happy-Mothers-Day-Embroidery-10873565-1.jpg", affiliate: "https://www.creativefabrica.com/product/floral-happy-mothers-day/ref/20531415/", category: "floral" },
  { title: "Mother's Day Floral Embroidery Designs", description: "A full bundle of floral Mother's Day designs for every project and hoop size.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/03/30/Mothers-Day-Floral-Embroidery-Designs-Embroidery-119037309-1.jpg", affiliate: "https://www.creativefabrica.com/product/mothers-day-floral-embroidery-designs/ref/20531415/", category: "floral" },

  // ── For the Grandmas ───────────────────────────────────────
  { title: "Floral Grammy", description: "Beautiful floral frame around 'Grammy' — a must-have gift for the Grammy in your family!", image: "https://www.creativefabrica.com/wp-content/uploads/2024/04/04/Floral-Grammy-Embroidery-94820416-1.jpg", affiliate: "https://www.creativefabrica.com/product/floral-grammy/ref/20531415/", category: "grandma" },
  { title: "Nona Mother's Day", description: "A sweet 'Nona' design with holiday warmth — the perfect gift for Italian grandmothers.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/20/Nona-Mothers-Day-Embroidery-29320204-2.jpg", affiliate: "https://www.creativefabrica.com/product/nona-mothers-day/ref/20531415/", category: "grandma" },
  { title: "Best Mawmaw Ever Mother Gift", description: "A loving tribute for Mawmaw — stitch it on an apron, tote, or sweatshirt for a gift she'll cherish.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/08/10/Best-Mawmaw-Ever-Mother-Gift-Embroidery-35935119-1.jpg", affiliate: "https://www.creativefabrica.com/product/best-mawmaw-ever-mother-gift/ref/20531415/", category: "grandma" },
  { title: "Grandma's Sunshine", description: "Warm and bright — 'Grandma's Sunshine' is perfect for kitchen towels, tote bags, and baby blankets.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/11/20/Grandmas-Sunshine-Embroidery-135882988-1.png", affiliate: "https://www.creativefabrica.com/product/grandmas-sunshine/ref/20531415/", category: "grandma" },
  { title: "My Favorite People Call Me Mimi", description: "One of America's favorite grandma names, beautifully lettered — a treasured gift for any Mimi.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/20/My-Favorite-People-Call-Me-Mimi-Embroidery-29320977-2.jpg", affiliate: "https://www.creativefabrica.com/product/my-favorite-people-call-me-mimi-31/ref/20531415/", category: "grandma" },
  { title: "Nana Flower", description: "Delicate florals surrounding 'Nana' — stitch it on a keychain, pillow, or towel for a heartfelt gift.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/29/Nana-Flower-Embroidery-29795687-1.jpg", affiliate: "https://www.creativefabrica.com/product/nana-flower-5/ref/20531415/", category: "grandma" },
  { title: "Grandma Sunflower", description: "Cheerful sunflower design personalized for Grandma — a timeless gift she'll display with pride.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/29/Grandma-Sunflower-Embroidery-29794533-1.jpg", affiliate: "https://www.creativefabrica.com/product/grandma-sunflower-3/ref/20531415/", category: "grandma" },
  { title: "My Favorite People Call Me Gigi", description: "The Gigi name in beautiful lettering — perfect for bags, shirts, and holiday gifts.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/19/My-Favorite-People-Call-Me-Gigi-Embroidery-29262605-2.jpg", affiliate: "https://www.creativefabrica.com/product/my-favorite-people-call-me-gigi-14/ref/20531415/", category: "grandma" },
  { title: "Nana Heart Sunflower", description: "A sunflower heart framing 'Nana' — warm, loving, and perfect for kitchen décor.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/25/Nana-Heart-Sunflower-Embroidery-29594256-2.jpg", affiliate: "https://www.creativefabrica.com/product/nana-heart-sunflower/ref/20531415/", category: "grandma" },
  { title: "Floral Grammy (Version 2)", description: "A second floral Grammy design with a more modern look — great for contemporary gifts.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/05/28/Floral-Grammy-Embroidery-98524193-1.jpg", affiliate: "https://www.creativefabrica.com/product/floral-grammy-3/ref/20531415/", category: "grandma" },

  // ── Sports & Hobby Moms ────────────────────────────────────
  { title: "Gymnastics MOM Applique Embroidery", description: "For the mom cheering from the sidelines — a bold applique design that showcases gymnastics pride.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/07/04/Gymnastics-MOM-Applique-Embroidery-Embroidery-101076943-1.jpg", affiliate: "https://www.creativefabrica.com/product/gymnastics-mom-applique-embroidery/ref/20531415/", category: "sports" },
  { title: "Baseball Mama Embroidery, Mother's Day", description: "Show off your baseball mama pride with this bold and sporty design — perfect for hats and shirts.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/04/14/Baseball-Mama-Embroidery-Mothers-Day-Embroidery-119879372-1.jpg", affiliate: "https://www.creativefabrica.com/product/baseball-mama-embroidery-mothers-day-2/ref/20531415/", category: "sports" },
  { title: "Tennis Mom", description: "For the court-side mama who serves love at home too — a fun design for shirts and tote bags.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/29/Tennis-Mom-Embroidery-29795310-1.jpg", affiliate: "https://www.creativefabrica.com/product/tennis-mom-18/ref/20531415/", category: "sports" },
  { title: "Mother's Day Gift | Football Mom ITH", description: "An in-the-hoop football mom design — perfect for creating a personalized gift that's game-day ready.", image: "https://www.creativefabrica.com/wp-content/uploads/2023/05/13/Mothers-Day-Gift-Football-Mom-ITH-Embroidery-69547994-1.png", affiliate: "https://www.creativefabrica.com/product/mothers-day-gift-football-mom-ith/ref/20531415/", category: "sports" },
  { title: "Basketball Mom Life", description: "Celebrate the basketball mom who never misses a game — stitch it on a hoodie or bag.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/29/Basketball-Mom-Life-Embroidery-29793286-1.jpg", affiliate: "https://www.creativefabrica.com/product/basketball-mom-life-3/ref/20531415/", category: "sports" },
  { title: "Softball Mama Embroidery, Mother's Day", description: "Sporty and sweet — the Softball Mama design is a home run for any sports-loving mom.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/04/14/Softball-Mama-Embroidery-Mothers-Day-Embroidery-119877116-1.jpg", affiliate: "https://www.creativefabrica.com/product/softball-mama-embroidery-mothers-day/ref/20531415/", category: "sports" },

  // ── Pet Moms (Fur Babies) ──────────────────────────────────
  { title: "Cat Mom", description: "For the cat mama who treats her fur babies like royalty — a sweet design for bags, shirts, and pillows.", image: "https://www.creativefabrica.com/wp-content/uploads/2023/05/11/Cat-Mom-Embroidery-69381344-1.jpg", affiliate: "https://www.creativefabrica.com/product/cat-mom-85/ref/20531415/", category: "pets" },
  { title: "Dog Mom Pet Lover", description: "Celebrate the dog mom in your life with this adorable paw-print design — a tail-wagging gift idea.", image: "https://www.creativefabrica.com/wp-content/uploads/2026/03/02/Dog-Mom-Pet-Lover-Embroidery-143707847-1.jpg", affiliate: "https://www.creativefabrica.com/product/dog-mom-pet-lover/ref/20531415/", category: "pets" },
  { title: "Best Cat Mom Ever, Cat Lover Quote", description: "A fun and bold lettering design for the world's greatest cat mom — great for shirts and tote bags.", image: "https://www.creativefabrica.com/wp-content/uploads/2026/03/02/Best-Cat-Mom-Ever-Cat-Lover-Quote-Embroidery-143706980-1.jpg", affiliate: "https://www.creativefabrica.com/product/best-cat-mom-ever-cat-lover-quote/ref/20531415/", category: "pets" },
  { title: "Dog Mom with Paw Print", description: "A sweet dog mom design featuring a paw print heart — perfect for the devoted dog mama.", image: "https://www.creativefabrica.com/wp-content/uploads/2026/02/15/Dog-Mom-with-Paw-Print-Embroidery-142499038-1.jpg", affiliate: "https://www.creativefabrica.com/product/dog-mom-with-paw-print-3/ref/20531415/", category: "pets" },
  { title: "Cute Cat Mom Paw Print", description: "Adorable cat paw print design for the proud cat mama — stitch it on a hoodie or tote.", image: "https://www.creativefabrica.com/wp-content/uploads/2026/02/23/Cute-Cat-Mom-Paw-Print-Embroidery-143072049-1.jpg", affiliate: "https://www.creativefabrica.com/product/cute-cat-mom-paw-print/ref/20531415/", category: "pets" },

  // ── Funny & Relatable Mom Life ─────────────────────────────
  { title: "Overstimulated Moms Club", description: "For the real moms who get it — a hilarious yet relatable design perfect for sweatshirts and tote bags.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/05/23/Overstimulated-Moms-Club-Embroidery-98224389-1.jpg", affiliate: "https://www.creativefabrica.com/product/overstimulated-moms-club-27/ref/20531415/", category: "funny" },
  { title: "Mom's Shit List", description: "A bold, funny design for the mom with a sense of humor — guaranteed laughs at every stitch.", image: "https://www.creativefabrica.com/wp-content/uploads/2021/10/28/Mom-Shit-List-Embroidery-19358260-1.jpg", affiliate: "https://www.creativefabrica.com/product/moms-shit-list/ref/20531415/", category: "funny" },
  { title: "Behind Every Mom is a Basket of Dirty Laundry", description: "Perfectly captures mom life — a funny, witty design that every mother will instantly relate to.", image: "https://www.creativefabrica.com/wp-content/uploads/2020/12/06/Behind-Every-Mom-is-A-Basket-Of-Laundry-Embroidery-7041237-1.jpg", affiliate: "https://www.creativefabrica.com/product/behind-every-mom-is-a-basket-of-dirty-laundry/ref/20531415/", category: "funny" },
  { title: "I Love Hot Moms, Funny Mother's Day", description: "Cheeky, fun, and guaranteed to make her smile — perfect for the mom who doesn't take herself too seriously.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/05/03/I-Love-Hot-Moms-Funny-Mothers-Day-Embroidery-96801483-1.jpg", affiliate: "https://www.creativefabrica.com/product/i-love-hot-moms-funny-mothers-day/ref/20531415/", category: "funny" },
  { title: "Mama Needs Coffee", description: "The universal mom truth, beautifully stitched — great for mugs, aprons, and kitchen towels.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/06/07/Mama-Needs-Coffee-Embroidery-99184152-1.jpg", affiliate: "https://www.creativefabrica.com/product/mama-needs-coffee-754/ref/20531415/", category: "funny" },
  { title: "Tired As a Mother", description: "Relatable, funny, and spot on — this design is a hit with every mom who needs a laugh.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/22/Tired-As-a-Mother-Embroidery-29448966-2.jpg", affiliate: "https://www.creativefabrica.com/product/tired-as-a-mother-109/ref/20531415/", category: "funny" },

  // ── New Moms & Baby (Nursery) ──────────────────────────────
  { title: "Mother and Child Silhouette", description: "A timeless silhouette of mother and child — a stunning design for nursery décor and keepsakes.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/04/14/Mother-and-Child-Silhouette-Embroidery-119883228-1.png", affiliate: "https://www.creativefabrica.com/product/mother-and-child-silhouette-7/ref/20531415/", category: "newmom" },
  { title: "Mother & Baby Giraffe", description: "Sweet and whimsical — a mother-and-baby giraffe design that's perfect for nursery quilts and bibs.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/03/07/Mother-Baby-Giraffe-Embroidery-117484435-1.png", affiliate: "https://www.creativefabrica.com/product/mother-baby-giraffe/ref/20531415/", category: "newmom" },
  { title: "Breastfeeding Mother in a Rocking Chair", description: "A tender, gentle design capturing a breastfeeding mother — a meaningful gift for new moms.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/01/11/Breastfeeding-Mother-in-a-Rocking-Chair-Embroidery-23316268-1.jpg", affiliate: "https://www.creativefabrica.com/product/breastfeeding-mother-in-a-rocking-chair-2/ref/20531415/", category: "newmom" },
  { title: "My 1st Mother's Day", description: "Celebrate her very first Mother's Day with this sweet commemorative design — a keepsake to cherish forever.", image: "https://www.creativefabrica.com/wp-content/uploads/2022/04/19/My-1st-Mothers-Day-Embroidery-29267164-1.jpg", affiliate: "https://www.creativefabrica.com/product/my-1st-mothers-day-52/ref/20531415/", category: "newmom" },
  { title: "Mama Bear and Cub Embroidery Design", description: "The perfect mama bear and cub — a heartwarming design for nursery quilts, baby blankets, and onesies.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/10/10/Mama-Bear-and-Cub-Embroidery-Design-Embroidery-132780154-1.jpg", affiliate: "https://www.creativefabrica.com/product/mama-bear-and-cub-embroidery-design/ref/20531415/", category: "newmom" },
  { title: "Baby Hand in Mother's Hand", description: "An incredibly tender design showing a baby's tiny hand in mom's — a perfect new-mother keepsake.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/06/16/Baby-Hand-in-Mothers-Hand-Embroidery-124194226-1.jpg", affiliate: "https://www.creativefabrica.com/product/baby-hand-in-mothers-hand/ref/20531415/", category: "newmom" },

  // ── Trending / General ─────────────────────────────────────
  { title: "Every Kind of Mom", description: "A fun and inclusive design celebrating every type of mom — from sporty to crafty to stay-at-home.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/04/04/Every-Kind-of-Mom-Embroidery-94874736-1.png", affiliate: "https://www.creativefabrica.com/product/every-kind-of-mom/ref/20531415/", category: "trending" },
  { title: "Best Mom Ever", description: "A classic 'Best Mom Ever' design in an elegant script — the perfect all-occasion gift.", image: "https://www.creativefabrica.com/wp-content/uploads/2023/04/04/Best-Mom-Ever-Embroidery-66164798-1-1.jpg", affiliate: "https://www.creativefabrica.com/product/best-mom-ever-1300/ref/20531415/", category: "trending" },
  { title: "Queen of Hearts: a Mother's Day Tribute", description: "She is the queen of every heart in the family — an elegant and meaningful Mother's Day design.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/05/14/Queen-of-Hearts-a-Mothers-Day-Tribute-Embroidery-97562281-1.png", affiliate: "https://www.creativefabrica.com/product/queen-of-hearts-a-mothers-day-tribute-9/ref/20531415/", category: "trending" },
  { title: "Mom, A Title Just Above Queen", description: "A witty and heartfelt design reminding everyone that no title matters more than 'Mom'.", image: "https://www.creativefabrica.com/wp-content/uploads/2023/04/02/Mom-a-Title-Just-Above-Queen-Embroidery-66041355-1.jpg", affiliate: "https://www.creativefabrica.com/product/mom-a-title-just-above-queen-227/ref/20531415/", category: "trending" },
  { title: "Mother's Love", description: "A beautiful script design — 'Mother's Love' — that works on everything from pillows to tote bags.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/04/04/Mothers-Love-Embroidery-94874607-1.png", affiliate: "https://www.creativefabrica.com/product/mothers-love-20/ref/20531415/", category: "trending" },
  { title: "Mama Love Script", description: "Flowing script lettering for 'Mama Love' — a versatile design for shirts, bags, and décor.", image: "https://www.creativefabrica.com/wp-content/uploads/2025/03/25/Mama-Love-Script-Embroidery-118742813-1.jpg", affiliate: "https://www.creativefabrica.com/product/mama-love-script/ref/20531415/", category: "trending" },
  { title: "She is Strong Fierce Brave", description: "An empowering tribute to every mom — 'Strong, Fierce, Brave' in bold, beautiful lettering.", image: "https://www.creativefabrica.com/wp-content/uploads/2023/04/27/She-is-Strong-Fierce-Brave-Embroidery-68199827-1.jpg", affiliate: "https://www.creativefabrica.com/product/she-is-strong-fierce-brave-2/ref/20531415/", category: "trending" },
  { title: "Mama Floral, Mother's Day", description: "A lush floral 'Mama' design overflowing with blooms — one of our most popular designs.", image: "https://www.creativefabrica.com/wp-content/uploads/2024/06/06/Mama-Floral-Mothers-Day-Embroidery-99148302-1.jpg", affiliate: "https://www.creativefabrica.com/product/mama-floral-mothers-day/ref/20531415/", category: "trending" },
];

const CATEGORIES = [
  { id: "all",      label: "All Designs",             icon: "✨" },
  { id: "floral",   label: "For the Classic Mom",     icon: "🌸" },
  { id: "grandma",  label: "For the Grandmas",        icon: "💛" },
  { id: "sports",   label: "Sports & Hobby Moms",     icon: "⚾" },
  { id: "pets",     label: "Pet Moms",                icon: "🐾" },
  { id: "funny",    label: "Funny & Relatable",       icon: "😂" },
  { id: "newmom",   label: "New Moms & Nursery",      icon: "🍼" },
  { id: "trending", label: "Trending Now",            icon: "🔥" },
];
